BITS 32

global TOK_NUMBER, TOK_STRING, TOK_SAY, TOK_PUST, TOK_BUDET
global TOK_TYPE_INT, TOK_TYPE_STR, TOK_IDENT, TOK_DOT, TOK_EOF

TOK_NUMBER    equ 1
TOK_STRING    equ 2
TOK_SAY       equ 3
TOK_PUST      equ 4
TOK_BUDET     equ 5
TOK_TYPE_INT  equ 6
TOK_TYPE_STR  equ 7
TOK_IDENT     equ 8
TOK_DOT       equ 9
TOK_EOF       equ 10
